name: AWS CDK Github Workflow

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm ci

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-north-1

      - name: Create .env file
        run: |
          echo "NOTIFICATIONS_EMAIL=${{ secrets.NOTIFICATIONS_EMAIL }}" >> .env

      - name: Install dependencies (Lambda Functions)
        run: |
          ls -l
          cd assets/lambda/BookingHandler && npm ci
          cd assets/lambda/BookingSeeder && npm ci
          cd assets/lambda/NotificationsHandler && npm ci

      - name: Build all assets (Lambda Functions)
        run: npm run build:assets:all

      - name: Deploy all CDK Stacks
        run: npm run cdk:deploy:all
